# 核心设置
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# 强制忽略主题测试文件
exclude:
  - docs
  - test
  - .github
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .travis.yml
  - CHANGELOG.md
  - minimal-mistakes-jekyll.gemspec
  - README.md
  - screenshot.png

# 集合配置
collections:
  bluetooth:
    output: true
    permalink: /bluetooth/:path/
  voice:
    output: true
    permalink: /voice/:path/
  jieli:
    output: true
    permalink: /jieli/:path/
  datasheet:
    output: true
    permalink: /datasheet/:path/

defaults:
  - scope:
      path: "_bluetooth"
      type: bluetooth
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"

  - scope:
      path: "_voice"
      type: voice
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"

# 其他必要配置
url: "https://blevoice.github.io"
baseurl: ""
